const dotenv = require('dotenv').config();

const PORT = process.env.PORT || 5000;
const MONGODB_CONNECTION_STRING= process.env.MONGODB_CONNECTION_STRING;
const ACCESS_TOKEN_SECRET= process.env.ACCESS_TOKEN_SECRET;
const REFRESH_TOKEN_SECRET= process.env.REFRESH_TOKEN_SECRET;
const CLOUDINARY_CLOUD_NAME=process.env.CLOUDINARY_CLOUD_NAME
const CLOUDINARY_API_KEY=process.env.CLOUDINARY_API_KEY
const CLOUDINARY_API_SECRET=process.env.CLOUDINARY_API_SECRET
const CLOUDINARY_UPLOAD_PRESET=process.env.CLOUDINARY_UPLOAD_PRESET

const AWS_S3_USER_ACCESS_KEY=process.env.IAM_USER_ACCESS_KEY
const AWS_S3_USER_SECRET_ACCESS_KEY=process.env.IAM_USER_SECRET_ACCESS_KEY
const AWS_S3_REGION=process.env.AWS_S3_REGION
const AWS_S3_BUCKET_NAME=process.env.AWS_S3_BUCKET_NAME

const GOOGLE_API_KEY=process.env.GOOGLE_API_KEY
const GOOGLE_PLACE_ID=process.env.GOOGLE_PLACE_ID

const YELP_API_KEY = process.env.YELP_API_KEY
const YELP_BUSINESS_ID = process.env.YELP_BUSINESS_ID

const NEU_ZIPCODE_API_KEY = process.env.NEU_ZIPCODE_API_KEY
const NEU_ZIPCODE_API_HOST= process.env.NEU_ZIPCODE_API_HOST

const POSTMAN_ZIP_CODE_API_HOST = process.env.POSTMAN_ZIP_CODE_API_HOST 
const POSTMAN_ZIP_CODE_API_KEY = process.env.POSTMAN_ZIP_CODE_API_KEY 

module.exports = {
 NEU_ZIPCODE_API_KEY,
 NEU_ZIPCODE_API_HOST,
 POSTMAN_ZIP_CODE_API_HOST,
 POSTMAN_ZIP_CODE_API_KEY,
 PORT,
 MONGODB_CONNECTION_STRING,
 ACCESS_TOKEN_SECRET,
 REFRESH_TOKEN_SECRET,
 CLOUDINARY_CLOUD_NAME,
 CLOUDINARY_API_KEY,
 CLOUDINARY_API_SECRET,
 CLOUDINARY_UPLOAD_PRESET,
 AWS_S3_USER_ACCESS_KEY,
 AWS_S3_USER_SECRET_ACCESS_KEY,
 AWS_S3_REGION,
 AWS_S3_BUCKET_NAME,
 GOOGLE_API_KEY,
 GOOGLE_PLACE_ID,
 YELP_API_KEY,
 YELP_BUSINESS_ID
}