const dotenv = require('dotenv').config();

const PORT = process.env.PORT || 5000;
const MONGODB_CONNECTION_STRING= process.env.MONGODB_CONNECTION_STRING;
const ACCESS_TOKEN_SECRET= process.env.ACCESS_TOKEN_SECRET;
const REFRESH_TOKEN_SECRET= process.env.REFRESH_TOKEN_SECRET;
CLOUDINARY_CLOUD_NAME=process.env.CLOUDINARY_CLOUD_NAME
CLOUDINARY_API_KEY=process.env.CLOUDINARY_API_KEY
CLOUDINARY_API_SECRET=process.env.CLOUDINARY_API_SECRET


module.exports = {
 PORT,
 MONGODB_CONNECTION_STRING,
 ACCESS_TOKEN_SECRET,
 REFRESH_TOKEN_SECRET,
 CLOUDINARY_CLOUD_NAME,
 CLOUDINARY_API_KEY,
 CLOUDINARY_API_SECRET
}